- name: Create Apache web servers shelly
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
		  
    - name: start Apache server
      service:
        name: httpd
        state: started
				  
    - name: Deploy static website 
      copy:
        src:  index.html
        dest: /var/www/html/
            
            
            
            
            
            