- name: Play Web - Create Apache web servers
    hosts: webserver
    become: True
    tasks:
        - name: install Apache
        yum:
          name: httpd
          state: present
		  
      - name: start Apache server
        service:
          name: httpd
          state: started
				  
      - name: Deploy static website 
        copy:
          src:  index.html
		  dest: /var/www/html/