set AWS_ACCESS_KEY_ID=AKIAWLY6SHELWM3DZ74X
set AWS_SECRET_ACCESS_KEY=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
set AWS_DEFAULT_REGION=us-east-1

echo printing variables 

echo %AWS_ACCESS_KEY_ID%
echo %AWS_SECRET_ACCESS_KEY%
echo %AWS_DEFAULT_REGION%