set AWS_ACCESS_KEY_ID=AKIAUK5CABWTN2MP2QWS
set AWS_SECRET_ACCESS_KEY=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
set AWS_DEFAULT_REGION=us-east-1

echo printing variables 

echo %AWS_ACCESS_KEY_ID%
echo %AWS_SECRET_ACCESS_KEY%
echo %AWS_DEFAULT_REGION%