set AWS_ACCESS_KEY_ID=AKIA4KUKIQIWGRY7B6OU
set AWS_SECRET_ACCESS_KEY=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
set AWS_DEFAULT_REGION=us-east-1

echo printing variables 

echo %AWS_ACCESS_KEY_ID%
echo %AWS_SECRET_ACCESS_KEY%
echo %AWS_DEFAULT_REGION%